### ISSUE TITLE
feature request ：support autotracking by Frigate

### ISSUE THREAD

**Issue by yangminglong** [themactep/thingino-firmware#237]
hello，Thank you very much for providing Thingino firmware. I refreshed the Thingino firmware for my XFP301-M and they worked very well.
I am currently using Frigate as an NVR to manage my multiple cameras. I would like to use the [AutoTracking](https://docs.frigate.video/configuration/autotracking) feature provided by Frigate for cameras that support PTZ.

My question is: I received a running log prompt from Frigate stating: `Disabling autotracking for thingino_205: ONVIF MoveStatus not supported` Does this require any adaptation in Thingino firmware?

**Comment by themactep** [comment]
i don't know about frigate but my hardware nvr and my mobile tinycam app both can control ptz on cameras running thingino over onvif.

**Comment by yangminglong** [comment]
> i don't know about frigate but my hardware nvr and my mobile tinycam app both can control ptz on cameras running thingino over onvif.

Thank you for your answer. Frigate and Thingino are truly great partners. On [Frigate](https://docs.frigate.video/), I can manually control the movement of the camera, but 'automatic tracking' is not possible. I think some adaptation may be needed here, and I will do more testing to provide more information.

**Comment by derzahla** [comment]
I just tried setting this up in Frigate as well.  Would be cool to get resolved on one end or the other

**Comment by gtxaspec** [comment]
@nschimme were you testing something like this? sounds familiar...

**Comment by derzahla** [comment]
Hm, frigate closed my case but per their documentation and camera test script provided, it would appear that my cinnado d1 camera running the latest build of thingino does suppose all required ONVIF functionatality:

```
python3 fovtest.py 
Connected to ONVIF camera
Created media service object
Media profiles
[{
    'Name': 'Profile_0',
    'VideoSourceConfiguration': {
        'Name': 'VideoSourceConfig',
        'UseCount': 2,
        'SourceToken': 'VideoSourceToken',
        'Bounds': {
            'x': 0,
            'y': 0,
            'width': 1920,
            'height': 1080
        },
        '_value_1': None,
        'Extension': None,
        'token': 'VideoSourceConfigToken',
        '_attr_1': {
    }
    },
    'AudioSourceConfiguration': None,
    'VideoEncoderConfiguration': {
        'Name': 'Profile_0_VideoEncoder',
        'UseCount': 1,
        'Encoding': 'H264',
        'Resolution': {
            'Width': 1920,
            'Height': 1080
        },
        'Quality': 0.0,
        'RateControl': {
            'FrameRateLimit': 0,
            'EncodingInterval': 0,
            'BitrateLimit': 0
        },
        'MPEG4': None,
        'H264': {
            'GovLength': 40,
            'H264Profile': 'High'
        },
        'Multicast': {
            'Address': {
                'Type': 'IPv4',
                'IPv4Address': None,
                'IPv6Address': None
            },
            'Port': 0,
            'TTL': 0,
            'AutoStart': False,
            '_value_1': None,
            '_attr_1': None
        },
        'SessionTimeout': datetime.timedelta(0),
        '_value_1': None,
        'token': 'Profile_0_VideoEncoderToken',
        '_attr_1': {
    }
    },
    'AudioEncoderConfiguration': None,
    'VideoAnalyticsConfiguration': None,
    'PTZConfiguration': {
        'Name': 'PTZCfg',
        'UseCount': 0,
        'NodeToken': 'PTZNodeToken',
        'DefaultAbsolutePantTiltPositionSpace': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace',
        'DefaultAbsoluteZoomPositionSpace': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace',
        'DefaultRelativePanTiltTranslationSpace': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace',
        'DefaultRelativeZoomTranslationSpace': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace',
        'DefaultContinuousPanTiltVelocitySpace': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace',
        'DefaultContinuousZoomVelocitySpace': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace',
        'DefaultPTZSpeed': {
            'PanTilt': {
                'x': 1.0,
                'y': 1.0,
                'space': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace'
            },
            'Zoom': {
                'x': 0.0,
                'space': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace'
            }
        },
        'DefaultPTZTimeout': datetime.timedelta(seconds=5),
        'PanTiltLimits': {
            'Range': {
                'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace',
                'XRange': {
                    'Min': 0.0,
                    'Max': 360.0
                },
                'YRange': {
                    'Min': 0.0,
                    'Max': 180.0
                }
            }
        },
        'ZoomLimits': {
            'Range': {
                'URI': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace',
                'XRange': {
                    'Min': 1.0,
                    'Max': 1.0
                }
            }
        },
        'Extension': {
            '_value_1': [
                <Element {http://www.onvif.org/ver10/schema}PTControlDirection at 0x74f143ad7e00>
            ],
            'PTControlDirection': None,
            'Extension': None
        },
        'token': 'PTZCfgToken',
        '_attr_1': {
            'MoveRamp': '0',
            'PresetRamp': '0',
            'PresetTourRamp': '0'
        }
    },
    'MetadataConfiguration': None,
    'Extension': None,
    'token': 'Profile_0',
    'fixed': True,
    '_attr_1': {
}
}, {
    'Name': 'Profile_1',
    'VideoSourceConfiguration': {
        'Name': 'VideoSourceConfig',
        'UseCount': 2,
        'SourceToken': 'VideoSourceToken',
        'Bounds': {
            'x': 0,
            'y': 0,
            'width': 1920,
            'height': 1080
        },
        '_value_1': None,
        'Extension': None,
        'token': 'VideoSourceConfigToken',
        '_attr_1': {
    }
    },
    'AudioSourceConfiguration': None,
    'VideoEncoderConfiguration': {
        'Name': 'Profile_1_VideoEncoder',
        'UseCount': 1,
        'Encoding': 'H264',
        'Resolution': {
            'Width': 640,
            'Height': 360
        },
        'Quality': 0.0,
        'RateControl': {
            'FrameRateLimit': 0,
            'EncodingInterval': 0,
            'BitrateLimit': 0
        },
        'MPEG4': None,
        'H264': {
            'GovLength': 40,
            'H264Profile': 'Main'
        },
        'Multicast': {
            'Address': {
                'Type': 'IPv4',
                'IPv4Address': None,
                'IPv6Address': None
            },
            'Port': 0,
            'TTL': 0,
            'AutoStart': False,
            '_value_1': None,
            '_attr_1': None
        },
        'SessionTimeout': datetime.timedelta(0),
        '_value_1': None,
        'token': 'Profile_1_VideoEncoderToken',
        '_attr_1': {
    }
    },
    'AudioEncoderConfiguration': None,
    'VideoAnalyticsConfiguration': None,
    'PTZConfiguration': {
        'Name': 'PTZCfg',
        'UseCount': 0,
        'NodeToken': 'PTZNodeToken',
        'DefaultAbsolutePantTiltPositionSpace': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace',
        'DefaultAbsoluteZoomPositionSpace': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace',
        'DefaultRelativePanTiltTranslationSpace': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace',
        'DefaultRelativeZoomTranslationSpace': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace',
        'DefaultContinuousPanTiltVelocitySpace': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace',
        'DefaultContinuousZoomVelocitySpace': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace',
        'DefaultPTZSpeed': {
            'PanTilt': {
                'x': 1.0,
                'y': 1.0,
                'space': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace'
            },
            'Zoom': {
                'x': 0.0,
                'space': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace'
            }
        },
        'DefaultPTZTimeout': datetime.timedelta(seconds=5),
        'PanTiltLimits': {
            'Range': {
                'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace',
                'XRange': {
                    'Min': 0.0,
                    'Max': 360.0
                },
                'YRange': {
                    'Min': 0.0,
                    'Max': 180.0
                }
            }
        },
        'ZoomLimits': {
            'Range': {
                'URI': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace',
                'XRange': {
                    'Min': 1.0,
                    'Max': 1.0
                }
            }
        },
        'Extension': {
            '_value_1': [
                <Element {http://www.onvif.org/ver10/schema}PTControlDirection at 0x74f143add0c0>
            ],
            'PTControlDirection': None,
            'Extension': None
        },
        'token': 'PTZCfgToken',
        '_attr_1': {
            'MoveRamp': '0',
            'PresetRamp': '0',
            'PresetTourRamp': '0'
        }
    },
    'MetadataConfiguration': None,
    'Extension': None,
    'token': 'Profile_1',
    'fixed': True,
    '_attr_1': {
}
}]
Chosen token
Profile_1
Creating PTZ object
Created PTZ service object
PTZ configurations:
{
    'Name': 'PTZCfg',
    'UseCount': 0,
    'NodeToken': 'PTZNodeToken',
    'DefaultAbsolutePantTiltPositionSpace': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace',
    'DefaultAbsoluteZoomPositionSpace': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace',
    'DefaultRelativePanTiltTranslationSpace': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace',
    'DefaultRelativeZoomTranslationSpace': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace',
    'DefaultContinuousPanTiltVelocitySpace': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace',
    'DefaultContinuousZoomVelocitySpace': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace',
    'DefaultPTZSpeed': {
        'PanTilt': {
            'x': 1.0,
            'y': 1.0,
            'space': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace'
        },
        'Zoom': {
            'x': 0.0,
            'space': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace'
        }
    },
    'DefaultPTZTimeout': datetime.timedelta(seconds=5),
    'PanTiltLimits': {
        'Range': {
            'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace',
            'XRange': {
                'Min': 0.0,
                'Max': 3700.0
            },
            'YRange': {
                'Min': 0.0,
                'Max': 1000.0
            }
        }
    },
    'ZoomLimits': {
        'Range': {
            'URI': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace',
            'XRange': {
                'Min': 1.0,
                'Max': 1.0
            }
        }
    },
    'Extension': {
        '_value_1': [
            <Element {http://www.onvif.org/ver10/schema}PTControlDirection at 0x74f1439367c0>
        ],
        'PTControlDirection': None,
        'Extension': None
    },
    'token': 'PTZCfgToken',
    '_attr_1': {
        'MoveRamp': '0',
        'PresetRamp': '0',
        'PresetTourRamp': '0'
    }
}

PTZ configuration options:
{
    'Spaces': {
        'AbsolutePanTiltPositionSpace': [
            {
                'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace',
                'XRange': {
                    'Min': 0.0,
                    'Max': 3700.0
                },
                'YRange': {
                    'Min': 0.0,
                    'Max': 1000.0
                }
            }
        ],
        'AbsoluteZoomPositionSpace': [
            {
                'URI': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace',
                'XRange': {
                    'Min': 1.0,
                    'Max': 1.0
                }
            }
        ],
        'RelativePanTiltTranslationSpace': [
            {
                'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace',
                'XRange': {
                    'Min': -3700.0,
                    'Max': 3700.0
                },
                'YRange': {
                    'Min': -1000.0,
                    'Max': 1000.0
                }
            },
            {
                'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationSpaceFov',
                'XRange': {
                    'Min': -100.0,
                    'Max': 100.0
                },
                'YRange': {
                    'Min': -100.0,
                    'Max': 100.0
                }
            }
        ],
        'RelativeZoomTranslationSpace': [
            {
                'URI': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace',
                'XRange': {
                    'Min': 0.0,
                    'Max': 0.0
                }
            }
        ],
        'ContinuousPanTiltVelocitySpace': [
            {
                'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace',
                'XRange': {
                    'Min': -1.0,
                    'Max': 1.0
                },
                'YRange': {
                    'Min': -1.0,
                    'Max': 1.0
                }
            }
        ],
        'ContinuousZoomVelocitySpace': [
            {
                'URI': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace',
                'XRange': {
                    'Min': 0.0,
                    'Max': 0.0
                }
            }
        ],
        'PanTiltSpeedSpace': [
            {
                'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace',
                'XRange': {
                    'Min': 1.0,
                    'Max': 1.0
                }
            }
        ],
        'ZoomSpeedSpace': [
            {
                'URI': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace',
                'XRange': {
                    'Min': 0.0,
                    'Max': 0.0
                }
            }
        ],
        'Extension': None,
        '_attr_1': None
    },
    'PTZTimeout': {
        'Min': datetime.timedelta(seconds=1),
        'Max': datetime.timedelta(seconds=100)
    },
    '_value_1': [
        <Element {http://www.onvif.org/ver10/schema}PTControlDirection at 0x74f14393d480>
    ],
    'PTControlDirection': None,
    'Extension': None,
    '_attr_1': None
}

PTZ service capabilities:
{
    '_value_1': None,
    'EFlip': False,
    'Reverse': False,
    'GetCompatibleConfigurations': False,
    '_attr_1': {
        'MoveStatus': 'false',
        'StatusPosition': 'true'
    }
}

PTZ status:
{
    'Position': {
        'PanTilt': {
            'x': 1776.0,
            'y': 944.0,
            'space': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace'
        },
        'Zoom': {
            'x': 1.0,
            'space': 'http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace'
        }
    },
    'MoveStatus': {
        'PanTilt': 'IDLE',
        'Zoom': 'IDLE'
    },
    'Error': None,
    'UtcTime': datetime.datetime(2024, 10, 6, 15, 54, 13, tzinfo=<isodate.tzinfo.Utc object at 0x74f144a30a40>),
    '_value_1': None,
    '_attr_1': None
}
YES - GetServiceCapabilities shows that the camera supports MoveStatus.
YES - MoveStatus is reporting IDLE.
YES - RelativeMove Pan/Tilt (FOV) is supported.
YES - RelativeMove Zoom is supported.
```

**Comment by gtxaspec** [comment]
check the discord chat history, I'm sure someone had it working before.

**Comment by Sparpet** [comment]
Im not up to date on the current motors implementation but from when I got this working, this is what I did:

-This is the ptz section of the onvif.conf file. We simulate continious motion request by issuing a relative move with a large position (9000)

`#PTZ
ptz=1
get_position=motors -p
move_left=motors -d g -x -9000
move_right=motors -d g -x 9000
move_up=motors -d g -y -9000
move_down=motors -d g -y 9000
move_stop=motors -d s
move_preset=/sbin/ptz_preset.sh %d
goto_home_position=motors -q -d b
get_presets=/sbin/ptz_preset.sh -g
is_moving=motors -b
jump_to_abs=motors -d h -x %f -y %f
jump_to_rel=motors -d g -x %f -y %f`

Move presets and get presets are crucial to get it working as they camera needs at least one to be they default position after tracking stops

In my case, I manually filled the ptz_presets.conf file to have at least one preset ready to reference on they frigate config.

https://github.com/themactep/thingino-firmware/tree/master/package/onvif-simple-server/files

For it to work you need to have the following on your frigate config:
-one onvif preset to return to
-one detection zone
-perform autotracking calibration

This si the frigate config I usted at the time

```
mqtt:
  enabled: false

cameras:
  desktop_thingino: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
      - path: rtsp://thingino:thingino@192.168.104.15:554/ch0
        roles:
        - detect
        - record
    detect:
      enabled: true
    record:
      enabled: false
    snapshots:
      enabled: false
    onvif:
      host: 192.168.104.15
      port: 80
      user: thingino
      password: thingino
      autotracking:
        enabled: true
        calibrate_on_startup: true
        zooming: disabled
        return_preset: Home
        required_zones:
        - zone_0

        movement_weights: 0.0, 1.0, 0.06328606605529785, 0.06929974094513923, 0.04489806159850092
    zones:
      zone_0:
        coordinates: 613,442,782,449,751,313,591,317
        inertia: 2
    motion:
      mask:
      - 578,247,370,836,93,805,130,237
      - 1838,130,1824,687,1204,643,1499,130
logger:
  logs:
    frigate.ptz.onvif: debug
    frigate.ptz.autotrack: debug
```
Couple of notes. 

You only need to leave calibrate on startup as true just once, it generates the movement weights you see on my file.

Return preset is they name of they preset youu define on ptz_presets.conf, i had issues with capitalization so try lower case if it doesnt detect the preset.

Let me know if you find any issues.

**Comment by yangminglong** [comment]
Thank you for your detailed answer, you saved my life. This is indeed useful.

I modified my configuration through SSH, and restarted my camera twice follow calibrate steps. and now my camera can automatically track (horizontal tracking is perfect, vertical tracking is the mirror).


`vi onvif.conf` 

```
#PTZ
ptz=1
max_step_x=3982
max_step_y=1100
get_position=motors -p
move_left=motors -d h -x 0
move_right=motors -d h -x 3982
move_up=motors -d h -y 1100
move_down=motors -d h -y 0
move_stop=motors -d s
move_preset=/sbin/ptz_presets %d
goto_home_position=motors -d b
get_presets=/sbin/ptz_presets -g
is_moving=motors -b #add
jump_to_abs=motors -d h -x %f -y %f
jump_to_rel=motors -d g -x %f -y %f
```
`ptz_presets.conf`
```
#0=Window,1200,360
0=Home,1550,400
1=
2=
3=
4=
5=
6=
7=
```

`frigate config.yaml`
```
...
    onvif:
      host: 192.168.10.207
      port: 80
      user: thingino
      password: thingino
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: true
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: false
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: disabled
        track:
          - person
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - steps
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: Home
...
```
