### ISSUE TITLE
Issue maintaining stable connection with Unifi Protect

### ISSUE THREAD

**Issue by achecchia** [themactep/thingino-firmware#466]
I was excited to try out Thingino and got the Wuuk PTZ as suggested by the creator. I have a unifi protect system which supports 3rd party cameras via ONVIF. when i bring the camera into Unifi Protect, it stays connected for about 8 seconds, looses connection, then reconnects, and the cycle repeats. I was wondering if it's an ONVIF standard issue or something different. i'm willing to help by submitting logs if this will help figure the issue out.

**Comment by wltechblog** [comment]
Unifi Protect's ONVIF support is still new and seems to be buggy. Unfortunately it is also a closed source product so we're not in a position to lend much assistance. We have suggested to others to create support tickets with that vendor and if they are able to reach out to us we're happy to talk with them. if you have any logs with detail please by all means share them, so far their product has been a black box for us.

**Comment by joeblack2k** [comment]
> I was excited to try out Thingino and got the Wuuk PTZ as suggested by the creator. I have a unifi protect system which supports 3rd party cameras via ONVIF. when i bring the camera into Unifi Protect, it stays connected for about 8 seconds, looses connection, then reconnects, and the cycle repeats. I was wondering if it's an ONVIF standard issue or something different. i'm willing to help by submitting logs if this will help figure the issue out.

The current ONVIF implementation in Thingino is broken. However, there's another open-source project that sends the correct SOAP requests. You can install it on a Docker server with the camera's RTSP URLs, and it will work like magic!

https://github.com/p10tyr/rtsp-to-onvif

**Comment by themactep** [comment]
@roleoroleo, take a look at this please.

**Comment by roleoroleo** [comment]
> The current ONVIF implementation in Thingino is broken. However, there's another open-source project that sends the correct SOAP requests. You can install it on a Docker server with the camera's RTSP URLs, and it will work like magic!
> 
> https://github.com/p10tyr/rtsp-to-onvif

I don't know what I'm doing wrong, but I have exaclty the same behavior using this container: 10 seconds stream and 10 seconds black screen.
I installed the container and configured with this config:
```
onvif:
  - name: BulletCam
    dev: enp1s0
    target:
      hostname: 192.168.0.236
      ports:
        rtsp: 554
        snapshot: 80
    highQuality:
      rtsp: /ch0
      snapshot: /x/image.cgi
      width: 2304
      height: 1296
      framerate: 25
      bitrate: 3072
      quality: 4
    ports:
      server: 1081
      rtsp: 1554
      snapshot: 1080
```

Click to "Adopt", the stream appears and then it starts the loop stream/black screen/stream/black screen.
Test with ODM is worse: there is no stream section at all.

![Image](https://github.com/user-attachments/assets/ab377e6e-f0e0-482f-ad0b-8220c5f82b95)
